### ISSUE TITLE
low-g botany broken

### ISSUE THREAD

**Issue by LounaCodes** [VampireFlower/StrawberryJamTAS#1]
in line 81/82 of log-g_botany, the TAS fails to make a reverse wavedash, because the dash ends 2 or 3 frames too early. Not sure what is intended to be done here. I tried fixing it by changing line 80 to `21, L`, but madeline ends up not getting enough speed from the ultra.

**Comment by Kataiser** [comment]
Please report desyncs in the #sj_tas_discussion channel in the celeste server. It does sync, so we can help you diagnose the issue on your end there
